### ISSUE TITLE
Build on macos fails for release 2.1.1

### ISSUE THREAD

**Issue by violette** [harrison314/BouncyHsm#101]
Hi,

I tried to regenerated my dylib based on **2.1.1** (same on 2.1.0) tag but I encounter this issue:
```
o
../src/Src/BouncyHsm.Pkcs11Lib/rpc/rpc.c:359:13: error: call to undeclared function 'sprintf_s'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
  359 |         if (sprintf_s(unknownBuffer, sizeof(unknownBuffer), "Unknown %i", rc) > 0)
      |             ^
../src/Src/BouncyHsm.Pkcs11Lib/rpc/rpc.c:359:13: note: did you mean 'sprintf'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:280:6: note: 'sprintf' declared here
  280 | int      sprintf(char * __restrict _LIBC_UNSAFE_INDEXABLE, const char * __restrict, ...) __printflike(2, 3) _LIBC_PTRCHECK_REPLACED(snprintf);
      |          ^
1 error generated.
make: *** [build/x64/rpc/rpc.o] Error 1
```

AI says: `sprintf_s is a Windows/MSVC safe function not available on macOS. The fix is to replace it with snprintf, which is the POSIX equivalent and already declared in scope.` 

Thanks!

**Comment by violette** [comment]
After applying the sprintf_s fix, the build fails with linker errors:
  ```
  Undefined symbols for architecture x86_64:
    "_GetCurrentComputerName", referenced from:
        _C_Initialize in bouncy-pkcs11.o
    "_freeProgramArgs", referenced from:
        _C_Initialize in bouncy-pkcs11.o
    "_getProgramArgs", referenced from:
        _C_Initialize in bouncy-pkcs11.o
```
  **platformHelper.c** only defines GetCurrentComputerName, getProgramArgs, and freeProgramArgs under #ifdef __linux__ and #ifdef _WIN32 — there is no **__APPLE__** branch. A macOS implementation is needed using
  gethostname and _NSGetArgc/_NSGetArgv from <crt_externs.h>.

  Additionally, build_macos/shim.h contains a typo: **GetCurrentCompiuterName** (extra 'i') instead of **GetCurrentComputerName**, so the stub it provides does not match the symbol name expected by the linker.

**Comment by violette** [comment]
Here is the patch 

[macos-build-fix.patch](https://github.com/user-attachments/files/29040614/macos-build-fix.patch)

**Comment by harrison314** [comment]
Thanks, I'll look into it.

**Comment by harrison314** [comment]
Thanks for the patch, I ended up doing it differently. I also made a Github Action so I could at least test the build on MacOs.
